version: "3.9"
services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: studentdb
    ports: ["3306:3306"]
    volumes: ["mysql_data:/var/lib/mysql"]
    networks: [smsnet]
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","localhost","-uroot","-proot"]
      interval: 10s
      retries: 5
  app:
    build: .
    depends_on:
      mysql: { condition: service_healthy }
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: studentdb
      DB_USER: root
      DB_PASSWORD: root
    ports: ["8080:8080"]
    networks: [smsnet]
volumes:
  mysql_data:
networks:
  smsnet:
